export const vacantes = [
    { title: "Desarrollador de nuevos negocios", 
    url: "https://s3-us-west-2.amazonaws.com/peaku-public/business/Company/logo_url/2078/descarga_(1).png", 
    company: "PeakU Inc", 
    location: "Remoto" },
    { title: "Analista QA", 
    url: "https://s3-us-west-2.amazonaws.com/peaku-public/business/Company/logo_url/75911/WhatsApp_Image_2022-11-30_at_3.30.37_PM.jpeg", 
    company: "Be Bolder", 
    location: "Remoto" },
    { title: "Auxiliar de compras", 
    url: "https://s3-us-west-2.amazonaws.com/peaku-public/business/Company/logo_url/80893/offiemedicas.png", 
    company: "OFFIMEDICAS S.A", 
    location: "Presencial" },
    { title: "Representante Servicio al Cliente",
    url: "https://s3-us-west-2.amazonaws.com/peaku-public/business/Company/logo_url/94664/international_smiles.jpg", 
    company: "SMILES", 
    location: "Medellin"    
    },
    { title: "Auxiliar de almacén",
    url: "https://s3-us-west-2.amazonaws.com/peaku-public/business/Company/logo_url/80893/offiemedicas.png", 
    company: "OFFIMEDICAS S.A", 
    location: "Presencial" },
    { title: "Director Comercial",
    url: "https://s3-us-west-2.amazonaws.com/peaku-public/business/Company/logo_url/52905/19.png", 
    company: "Bankuish", 
    location: "Remoto en Brazil" },
    { title: "Supervisor Visitador Médico",
    url: "https://s3-us-west-2.amazonaws.com/peaku-public/business/Company/logo_url/11337/Dentaid.png", 
    company: "Dentaid", 
    location: "Presencnial(Bogotá)" },
    { title: "SSR Full Stack Developer",
    url: "https://s3-us-west-2.amazonaws.com/peaku-public/business/Company/logo_url/4310/vichara.jpeg", 
    company: "VICHARA TECH", 
    location: "Remoto Colombia" },
    { title: "Especialista en marketing",
    url: "https://s3-us-west-2.amazonaws.com/peaku-public/business/Company/logo_url/40668/descarga.png", 
    company: "Fourier Analytics", 
    location: "Remoto" },
  ];
  